# Generated by Django 4.0.3 on 2022-06-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('new', 'new'), ('old', 'old'), ('used', 'used')], max_length=200, null=True)),
                ('decsription', models.CharField(blank=True, max_length=200, null=True)),
                ('tag', models.ManyToManyField(max_length=200, null=True, to='test_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('delivered', 'delivered'), ('pending', 'pending')], max_length=200, null=True)),
                ('customer', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.customer')),
                ('product', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.product')),
            ],
        ),
    ]
